### ISSUE TITLE
移動權限有關問題

### ISSUE THREAD

**Issue by Frog6605** [mcg25035/ResidenceFly#1]
擁有領地管理員權限且該領地玩家移動權限為false時，領地管理員進入領地開啟飛行後，擁有者拔除該管理員的權限(指令pdel跟pset admin f)，理應被踢出領地，但在飛行狀態下無法被踢出領地，即便解除該玩家飛行狀態仍然一樣。

**Comment by mcg25035** [comment]
The bug was fixed in this update.
Report again if it is not solved.
